server-app/hitsbook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(r'administracion/', include(('tasksmanager.urls', 'tasksmanager'), namespace="tasksmanager")),
    path(r'', include(('taskslist.urls', 'taskslist'), namespace="taskslist")),
]

server-app/taskslist/urls.py
from django.urls import path

from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

server-app/tasksmanager/urls.py
from django.urls import path

from .views import HomeView, NewTaskView, EditTaskView, DeleteTaskView

urlpatterns = [
    path('tarea/<int:pk>/eliminar', DeleteTaskView.as_view(), name='delete'),
    path('tarea/<int:pk>', EditTaskView.as_view(), name='edit'),
    path('tarea', NewTaskView.as_view(), name='new'),
    path('', HomeView.as_view(), name='home'),
]

server-app/taskslist/models.py
from django.db import models

# Create your models here.

server-app/tasksmanager/models.py
from django.db import models

STATUSES = (
    ('created', 'creada'),
    ('revised', 'revisada'),
    ('marked', 'marcada'),
    ('deleted', 'deleted'),
)

class Task(models.Model):
    title = models.CharField(max_length=128)
    status = models.CharField(max_length=32, choices=STATUSES, default=STATUSES[0][0])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

server-app/tasksmanager/forms/edit_task_form.py
from django.forms import ModelForm
from tasksmanager.models import Task

class EditTaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'status']

server-app/tasksmanager/forms/new_task_form.py
from django.forms import ModelForm
from tasksmanager.models import Task

class NewTaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title']
        labels = {
            'title': 'Tarea',
        }
        help_texts = {
            'title': 'Ingresa la descripción de la tarea',
        }
        # attrs = {
        #     'title': {
        #         'placeholder': 'Escribir tarea',
        #     }
        # }

server-app/taskslist/views/home_view.py
from django.views.generic import ListView

from tasksmanager.models import Task

class HomeView(ListView):
    model = Task
    template_name = "taskslist/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = Task.objects.all()
        return context

server-app/tasksmanager/views/delete_task_view.py
from django.urls import reverse_lazy
from django.views.generic import DeleteView

from tasksmanager.models import Task

class DeleteTaskView(DeleteView):
    template_name = "tasksmanager/delete.html"
    model = Task
    success_url = reverse_lazy('tasksmanager:home')

server-app/tasksmanager/views/edit_task_view.py
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView

from tasksmanager.models import Task
from tasksmanager.forms import EditTaskForm

class EditTaskView(UpdateView):
    template_name = "tasksmanager/new.html"
    form_class = EditTaskForm
    model = Task
    success_url = reverse_lazy('tasksmanager:home')

    # def form_valid(self, form):
    #     form.save()
    #     return super().form_valid(form)

server-app/tasksmanager/views/home_view.py
from django.shortcuts import render
from django.views.generic import ListView

from tasksmanager.models import Task

class HomeView(ListView):
    model = Task
    template_name = "tasksmanager/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = Task.objects.all()
        return context

server-app/tasksmanager/views/new_task_view.py
from django.urls import reverse_lazy
from django.views.generic.edit import FormView

from tasksmanager.forms import NewTaskForm

class NewTaskView(FormView):
    template_name = "tasksmanager/new.html"
    form_class = NewTaskForm
    success_url = reverse_lazy('tasksmanager:home')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

server-app/taskslist/templates/taskslist/base.html
{% extends 'base.html' %}

{% block title %}
Listado
{% endblock title %}

{% block header %}
<nav class="navbar static-top">
    <div class="container align-items-center justify-content-center">
        <a class="navbar-brand" href="{% url 'taskslist:home' %}">hitsbook</a>
    </div>
</nav>
<div class="tool">
  <div class="container">
    <a class="btn btn-primary btn-lg tasks-manager" href="{% url 'tasksmanager:home' %}" alt="Administrar tareas">
      <i class="fas fa-list"></i> Administrar tareas
    </a>
  </div>
</div>
{% endblock header %}

server-app/taskslist/templates/taskslist/home.html
{% extends 'taskslist/base.html' %}

{% block content %}
<div id="tasksmanager">
    <div class="list">
      {% if tasks %}
        <ul>
          {% for task in tasks %}
          <li class="card border-primary task-{{task.status}}">
              <div class="card-body text-primary">
                {{task.title}}
              </div>
              <div class="card-footer text-muted">
                  {{task.created_at|date:'Y-m-d H:i'}}
              </div>
          </li>
          {% endfor %}
        </ul>
      {% else %}
        <div class="alert alert-danger" role="alert">
          No hay tareas
        </div>
      {% endif %}
    </div>
  </div>
{% endblock content %}

server-app/tasksmanager/templates/tasksmanager/base.html
{% extends 'base.html' %}

{% block title %}
Listado
{% endblock title %}

{% block header %}
<nav class="navbar static-top">
    <div class="container align-items-center justify-content-center">
        <a class="navbar-brand" href="{% url 'taskslist:home' %}">hitsbook</a>
    </div>
</nav>
{% endblock header %}

server-app/tasksmanager/templates/tasksmanager/delete.html
{% extends 'tasksmanager/base.html' %}

{% block content %}
<div id="tasksmanager">
  <form method="post">
    <legend>Eliminar tarea</legend>
    <div>
      <div>Título: {{task.title}}</div>
      <div>Creada: {{task.created_at|date:'Y-m-d H:i'}}</div>
      <div>Estado: {{task.status}}</div>
    </div>
    <p>¿Desea eliminar la tarea?</p>
    <div class="form-actions">
      <a href="{% url 'tasksmanager:home' %}" class="btn btn-secondary btn-lg">
        Cancelar
      </a>
      <input type="submit" class="btn btn-success btn-lg" value="Confirm">
    </div>
    {% csrf_token %}
  </form>
</div>
{% endblock content %}

server-app/tasksmanager/templates/tasksmanager/home.html
{% extends 'tasksmanager/base.html' %}

{% block content %}
<div id="tasksmanager">
  <div class="tool">
    <a class="btn btn-primary btn-lg add-task" href="{% url 'tasksmanager:new' %}">
        <i class="fas fa-plus"></i> Agregar una tarea
    </a>
  </div>

  <div class="list">
    {% if tasks %}
      <ul>
        {% for task in tasks %}
        <li class="card border-primary task-{{task.status}}">
            <div class="card-body text-primary">
              <p>{{task.title}}</p>

              <p>
                {{task.created_at|date:'Y-m-d H:i'}}
              </p>
              
              <p>
                {{task.status}}
              </p>

              <div>
                  <a class="btn" href="{% url 'tasksmanager:edit' task.id %}" alt="Editar">
                    <i class="fas fa-edit"></i>
                  </a>
                  <a class="btn" href="{% url 'tasksmanager:delete' task.id %}" alt="Eliminar">
                    <i class="fas fa-trash-alt"></i>
                  </a>
              </div>
            </div>
        </li>
        {% endfor %}
      </ul>
    {% else %}
      <div class="alert alert-danger" role="alert">
        No hay tareas
      </div>
    {% endif %}
  </div>
</div>
{% endblock content %}

server-app/tasksmanager/templates/tasksmanager/new.html
{% extends 'tasksmanager/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div id="tasksmanager">
  <form method="post">
    <legend>Nueva tarea</legend>

    {{ form|crispy }}

    <div class="form-actions">
      <a href="{% url 'tasksmanager:home' %}" class="btn btn-secondary btn-lg">
        Cancelar
      </a>
      <button type="submit" class="btn btn-success btn-lg">
        Guardar
      </button>
    </div>

    {% csrf_token %}
  </form>
</div>
{% endblock content %}

server-app/templates/_css.html
{% load static %}
<link rel="stylesheet" href="{% static '/css/hitsbook.css' %}">

server-app/templates/_js.html
{% load static %}
<script src="{% static '/js/hitsbook.js' %}"></script>

server-app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="Prueba de manejo de tareas">
    <meta name="author" content="Ismael Ramos">

    <title>Administración de tareas {% block title %}{% endblock title %}</title>

    <link rel="manifest" href="{% static 'manifest.json' %}" />
    {% include '_css.html' %}
</head>

<body>
    <header>
        {% block header %}{% endblock header %}
    </header>

    <div class="container">
        {% block content %}{% endblock content %}
    </div>
    
    {% include '_js.html' %}
</body>
</html>